### ISSUE TITLE
Parse the README on github and add it to model groups as well as the description

### ISSUE THREAD

**Issue by Avsecz** [kipoi/website#82]
## Model groups
When viewing the model group page: 
![image](https://user-images.githubusercontent.com/10011161/47714424-22d06a80-dc3d-11e8-9cbd-c5f7dd6ec18f.png)

The readme should be displayed somewhere on the page. Preferably bellow as on the github page. @gagneur @s6juncheng what do you think? 

Here is how the github page is rendered:
![image](https://user-images.githubusercontent.com/10011161/47714554-75118b80-dc3d-11e8-96ab-a8dadcae7cef.png)

- [ ] we should also paginate the model groups in case there are too many models like in http://kipoi.org/models/pwm_HOCOMOCO/human/ 

## Model detail page
![image](https://user-images.githubusercontent.com/10011161/47714644-bace5400-dc3d-11e8-9f1b-ec8a0272266d.png)

We should also parse the README and display it in the `doc` field as shown on the github page:

![image](https://user-images.githubusercontent.com/10011161/47714667-c883d980-dc3d-11e8-9127-df81cd42cfdb.png)

## Tasks

- [ ] code to get the directory where the README file should reside:
  - model detail view
    - `model_dir = kipoi.get_source(current_app.config['SOURCE']).get_model_dir(model_name)`
  - model group view
     - `group_dir = os.path.join(kipoi.get_source(current_app.config['SOURCE']).local_path, group_name)`
  - model group view
     - `group_dir = os.path.join(kipoi.get_source(current_app.config['SOURCE']).local_path, group_name)`

- [x] implement the nice markdown parser to convert readme pages from markdown to html:
  - Use: https://pypi.org/project/pypandoc/  or http://flask.pocoo.org/snippets/19/
  - on the flask backend, run:
    - model detail view:
      - add the parsing code here: https://github.com/kipoi/website/blob/master/app/models/views.py#L300-L304
      - Maybe concatenate it first with `model.info.doc` and then render it as html
    - model list view:
      - add it somewhere here https://github.com/kipoi/website/blob/master/app/models/views.py#L333
    - model group view:
      - add it somewhere here: https://github.com/kipoi/website/blob/master/app/models/views.py#L202
- [x] inject the rendered html to the template
  - model detail view: https://github.com/kipoi/website/blob/master/app/models/templates/models/model_details.html#L77
  - group_list: after the table: https://github.com/kipoi/website/blob/master/app/models/templates/models/group_list.html#L62
  - mode_list: after the table: https://github.com/kipoi/website/blob/master/app/models/templates/models/model_list.html#L54

**Comment by shabnamsadegh** [comment]
following issues solved:
1. python does not handle case-sensitive path handling in unix file system. resolved issue with readme.md vs README.md
2. by injecting the readme, when there is an image, it causes an overflow in html. resolved issue by adding following jquery in index.html and group_index.html:
$('.readmecontent img').css('max-width','100%')

**Comment by Avsecz** [comment]
closed by https://github.com/kipoi/website/pull/85
